# -*- coding: utf-8 -*-
"""test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J6ef96dFkyqFeDWnyI7H67yX6J-TLM1N
"""

class car:
  def _init_(self, speed):
    self.__speed = speed